### ISSUE TITLE
请求动态时报错

### ISSUE THREAD

**Issue by Tang121337** [sandboxdream/bilibili_lottery_dynamic_del#2]
填入key后报错怎么办

**Comment by Tang121337** [comment]
详情为打开main后闪退 拖入vscode后显示data_list = data['data']['cards']  KeyError: cards

**Comment by sandboxdream** [comment]
麻烦提供一下b站uid，我看看api返回的内容

**Comment by sandboxdream** [comment]
或者在代码第39行后加入一行输出一下data_list
即
```
  data = json.loads(res.text)
  print(data_list)
  data_list = data['data']['cards']
```
把输出内容发一下

**Comment by Tang121337** [comment]
![SGASIPFTJS4(HX6 YBRSA N](https://user-images.githubusercontent.com/30113090/143377514-9aa3ce8b-ed2d-4758-a294-c274e612c8c4.png)
加入后输出

**Comment by Tang121337** [comment]
> 麻烦提供一下b站uid，我看看api返回的内容

"uid" : 503299825,

**Comment by sandboxdream** [comment]
额，打错了。
应该输出data
也就是把第40行改成
print(data)

**Comment by sandboxdream** [comment]
我这里访问这个uid的返回好像没啥问题

**Comment by Tang121337** [comment]
> 应该输出data 也就是把第40行改成print(data)

![2](https://user-images.githubusercontent.com/30113090/143437520-1574fac8-81fd-461c-b9b9-0c8cc164ea30.png)
奇怪

**Comment by Tang121337** [comment]
> 我这里访问这个uid的返回好像没啥问题

![O63%O(U4 C)6DH2$ MDUO02](https://user-images.githubusercontent.com/30113090/143445796-1b98536e-1f90-441e-a45a-fb23a22c926d.png)
数据错误了=

**Comment by sandboxdream** [comment]
貌似暂时无法确认问题发生的原因。可能是之前请求太频繁导致b站api封ip或者是b站对user-agent做出了限制。

可能要等我周末放假才能确定原因

**Comment by Tang121337** [comment]
> 
好辛苦了 我去打包发给别人试试

**Comment by Tang121337** [comment]
> 暂时无法确认问题发生的原因。
> 
> 可能要等我周末放假才能确定原因

好辛苦了

**Comment by sandboxdream** [comment]
我好像找到问题了你用的python版本是多少

**Comment by Tang121337** [comment]
> 我好像找到了问题了你用的python版本是多少
> […](#)
> ------------------ 原始邮件 ------------------- 发件人: ***@ *** .***>;发送时间：2021年11月25日(1)晚上10点：晚上11点：***@***.***>抄送：***@***.* **>; ***@***.***>;主题：回复：[sandboxdream/bilibili_lottery_dynamic_del] 请求动态时报错（问题#2）暂时无法确认问题的原因。直接回复此邮件，在GitHub上查看，或取消订阅。使用适用于iOS或Android的GitHub Mobile随时随地的分类通知。
3.8.1

**Comment by Tang121337** [comment]
> 我好像找到了问题了你用的python版本是多少

![QPZY3V4~7~F@Q8 $WANBB4G](https://user-images.githubusercontent.com/30113090/143543479-069c2fbc-8821-4194-8d5a-19079c6ec51a.png)

**Comment by sandboxdream** [comment]
在第38行后加一下这个
print(url(config['uid']))
看一下请求的网址

**Comment by sandboxdream** [comment]
修了一下，拉取一下更新看看能用吗?

**Comment by Tang121337** [comment]
> 修一下，拉取一下更新看看能用吗？

不好意思
不好意思

**Comment by Tang121337** [comment]
> 修一下，拉取一下更新看看能用吗？

上周有事出去了 没来得及回复

**Comment by Tang121337** [comment]
> 修一下，拉取一下更新看看能用吗？

![1}7` L70$LG9FE(_BY0 WUT](https://user-images.githubusercontent.com/30113090/144355695-0f01ed6a-8939-4842-977c-b40a325f2dce.png)
有那么yisisi一丝丝迷茫

**Comment by sandboxdream** [comment]
这个是可以使用的正常提示。
这个提示要么是检查的动态不是转发的动态，要么是转发源动态被删除。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月2日(星期四) 中午12:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sandboxdream/bilibili_lottery_dynamic_del] 请求动态时报错 (Issue #2)





  
修一下，拉取一下更新看看能用吗？
  

 有那么yisisi一丝丝迷茫
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tang121337** [comment]
> 

![image](https://user-images.githubusercontent.com/30113090/144553273-636db3d4-e90f-4dc3-838a-0963c6b3c223.png)
删不太掉 我现在4000多条动态了=_=我想直接全删了把动态

**Comment by sandboxdream** [comment]
可以试试把判断标准抽奖的时间部分删了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 下午2:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sandboxdream/bilibili_lottery_dynamic_del] 请求动态时报错 (Issue #2)





   

 删不太掉 我现在4000多条动态了=_=我想直接全删了把动态
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tang121337** [comment]
> 可以试试把判断标准抽奖的时间部分删了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月3日(星期五) 下午2:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [sandboxdream/bilibili_lottery_dynamic_del] 请求动态时报错 (Issue #2) 删不太掉 我现在4000多条动态了=_=我想直接全删了把动态 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

![image](https://user-images.githubusercontent.com/30113090/144695105-a9a3828f-ae22-4128-9cae-efd7390b9753.png)

**Comment by Tang121337** [comment]
> 可以头脑判断抽奖的时间部分标准了
> […](#)
> ------------------ 原始邮件 ------------------- 发件人: ***@ ***.***>; 发送时间：2021年12月3日（适用）下午2:00发送：***@***.***>; 抄送：***@***.***>; ***@***.***>; 主题: Re: [sandboxdream/bili_lottery_dynamic_del] 请求动态时报错（Issue #2）直接回复此邮件，在 GitHub 上查看，或取消订阅。使用适用于 iOS 或 Android 的 GitHub Mobile 随时随地分类通知。

能不能直接把所有动态全删了 估计号黑了得养一段时间

**Comment by sandboxdream** [comment]
添加删除全部动态功能，此issue关闭
